rest:

  - resource: "https://api.bitpanda.com/v1/ticker"
    scan_interval: 600
    sensor:
      - name: "bp_BTC_EUR"
        value_template: "{{ value_json['BTC']['EUR'] }}"
        unit_of_measurement: "€"
        unique_id: "bp_BTC_EUR"
      - name: "bp_ETH_EUR"
        value_template: "{{ value_json['ETH']['EUR'] }}"
        unit_of_measurement: "€"
        unique_id: "bp_ETH_EUR"
      - name: "bp_XRP_EUR"
        value_template: "{{ value_json['XRP']['EUR'] }}"
        unit_of_measurement: "€"
        unique_id: "bp_XRP_EUR"
      - name: "bp_XLM_EUR"
        value_template: "{{ value_json['XLM']['EUR'] }}"
        unit_of_measurement: "€"
        unique_id: "bp_XLM_EUR"
      - name: "bp_SOL_EUR"
        value_template: "{{ value_json['SOL']['EUR'] }}"
        unit_of_measurement: "€"
        unique_id: "bp_SOL_EUR"
      - name: "bp_HBAR_EUR"
        value_template: "{{ value_json['HBAR']['EUR'] }}"
        unit_of_measurement: "€"
        unique_id: "bp_HBAR_EUR"
      - name: "bp_XAU_EUR"
        value_template: "{{ value_json['XAU']['EUR'] }}"
        unit_of_measurement: "€"
        unique_id: "bp_XAU_EUR"